default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yaus_development

test:
  <<: *default
  database: yaus_test

production:
  <<: *default
  database: yaus_production
  username: postgres
  password: postgres
  host: postgresql-master
  port: 5432
